/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login.Admin;

import login.Admin.GeneradorCorreoBienvenida;
import ProyectoTap.ValidadorTexto;
import com.mycompany.java_crud_mysqlfinal.CConexion;
import com.mycompany.java_crud_mysqlfinal.CUsuarios;
import elementos.Correo;
import java.awt.Color;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.mail.MessagingException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import login.Ingreso;
import login.PruebasYComponentes.PanelTransparente;


/**
 *
 * @author enriq
 */
public class Registro extends javax.swing.JFrame {
    int acces;
    CUsuarios objetoUsuarios;
    CConexion objetoConexion;
    Correo miCorreo;
    String remitente;
    String contraseña; 
    GeneradorCorreoBienvenida pdf;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro.class.getName());

    /**
     * Creates new form LOGIN
     * @param array
     * @param objetoUsuarios
     */
    
    public Registro(int acces,CUsuarios objetoUsuarios) { // recibe el Array real
        this.acces = acces; // usa el mismo Array que el LOGIN principal
        initComponents();
        lblAviso.setVisible(false);
        this.objetoUsuarios=objetoUsuarios;
        miCorreo = new Correo();
        remitente = "enriquezvalenciaoliver501@gmail.com";
        contraseña = "cile mzdw ytpo srnu";
        txtAsignado.setEnabled(false);
        btnEnviar.setEnabled(false);
        pdf = new GeneradorCorreoBienvenida();
        ((PanelTransparente) jPanel1).setColorFondo(Color.cyan); // Negro
        ((PanelTransparente) jPanel1).setTransparencia(0.4f); // 70%
        
        ((PanelTransparente) jPanel3).setColorFondo(Color.cyan); // Negro
        ((PanelTransparente) jPanel3).setTransparencia(0.4f); // 70%
        Imagen();
    }
    
    public void Imagen() {
        // Ruta relativa al paquete src/login/Imagenes/
        
        String rutaImagen = "/login/Imagenes/cruz.jpg"; // Asegúrate de usar el nombre y extensión correctos

        java.net.URL recurso = getClass().getResource(rutaImagen);
    
        if (recurso != null) {
            ImageIcon icono = new ImageIcon(recurso);

            // Escalar imagen al tamaño del JLabel
            int ancho = jLabel1.getWidth();
            int alto = jLabel1.getHeight();
            Image imagenEscalada = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

            jLabel1.setIcon(new ImageIcon(imagenEscalada));
        } else {
            JOptionPane.showMessageDialog(null, "⚠ Imagen no encontrada en: " + rutaImagen);
            jLabel1.setIcon(null);
        }
    }
    
    
    
    public void enviarCorreo(){
        String con = new String(pswContra.getPassword());
        miCorreo.setRemitente(remitente,contraseña);
        miCorreo.setDestinatario(txtCorreo.getText());
        miCorreo.setContenido("Creacion de usuario","Bienvenido, a continuación tu información de usuario");
        pdf.escribir(txtCorreo.getText(), con,txtNombre.getText());
        try {
        // Envía el correo
        String ruta = System.getProperty("user.home") + "/Desktop/PDFalCorreo/"+txtNombre.getText()+".pdf";
        miCorreo.agregarArchivo(ruta);
        miCorreo.enviarCorreo();

        } catch (Exception e) {
            lblAviso.setText("Correo no envíado, revisa que el correo sea válido");
            lblAviso.setForeground(Color.red);
            
        }
    }
    
    public boolean comparar(JTextField correo){
        objetoConexion=new CConexion();
        Statement st;
        String sql = "";
        sql="SELECT * FROM usuarios;";
        try{
            st= objetoConexion.estableceConexion().createStatement();
            ResultSet rs =st.executeQuery(sql);
            while (rs.next()){
                    if (rs.getString(3).equals(correo.getText())){
                        return true;
                    }       
            }
        }
        catch(SQLException e){JOptionPane.showMessageDialog(null, " No se pudo acceder a la BD");}
        return false;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        lblAviso2 = new javax.swing.JLabel();
        lblAviso1 = new javax.swing.JLabel();
        jPanel1 = new PanelTransparente();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pswContra = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        lblAviso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pswContra1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAsignado = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rbtnCajero = new javax.swing.JRadioButton();
        rbtnAlmacenista = new javax.swing.JRadioButton();
        rbtnAdministrador = new javax.swing.JRadioButton();
        jPanel3 = new PanelTransparente();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAviso2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAviso2.setForeground(new java.awt.Color(0, 0, 153));
        lblAviso2.setText("El correo debe ser de dominio Gmail o hotmaily nocontener espacios");
        lblAviso2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(lblAviso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 560, 20));

        lblAviso1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAviso1.setForeground(new java.awt.Color(0, 0, 153));
        lblAviso1.setText("La contraseña debe de tener 8 componentes, minimo una mayuscula , un numero y un caracter");
        lblAviso1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(lblAviso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 560, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jLabel3.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CORREO:");

        txtCorreo.setText("@gmail.com");
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");

        pswContra.setText("jPasswordField1");
        pswContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pswContraMouseClicked(evt);
            }
        });
        pswContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswContraActionPerformed(evt);
            }
        });

        btnAceptar.setText("Crear");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblAviso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAviso.setForeground(new java.awt.Color(255, 0, 0));
        lblAviso.setText("La contraseña no coincide, intenta de nuevo");

        jLabel5.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Repetir ");

        pswContra1.setText("jPasswordField1");
        pswContra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pswContra1MouseClicked(evt);
            }
        });
        pswContra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswContra1ActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("nombre:");

        jLabel7.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Acceso:");

        jLabel8.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Asignado:");

        txtAsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAsignadoActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar correo");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver al menú anterior");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jPanel2.setOpaque(false);

        grupo.add(rbtnCajero);
        rbtnCajero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnCajero.setForeground(new java.awt.Color(255, 255, 255));
        rbtnCajero.setText("Cajero");

        grupo.add(rbtnAlmacenista);
        rbtnAlmacenista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnAlmacenista.setForeground(new java.awt.Color(255, 255, 255));
        rbtnAlmacenista.setText("Almacenista");
        rbtnAlmacenista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAlmacenistaActionPerformed(evt);
            }
        });

        grupo.add(rbtnAdministrador);
        rbtnAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        rbtnAdministrador.setText("Administrador");
        rbtnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbtnCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnAlmacenista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtnAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(rbtnAlmacenista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnCajero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnAdministrador)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(59, 59, 59)
                                .addComponent(pswContra1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(pswContra))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(64, 64, 64)
                                .addComponent(txtCorreo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7)
                        .addGap(1312, 1312, 1312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1271, 1271, 1271))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pswContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pswContra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblAviso))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptar)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(jButton1))
                .addGap(76, 76, 76)
                .addComponent(btnEnviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 560, 350));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("ROG Fonts", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("                          Registro");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 560, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Imagenes/cruz.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
        txtCorreo.setText("");
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void pswContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswContraMouseClicked
        // TODO add your handling code here:
        pswContra.setText("");
        
        lblAviso1.setText("La contraseña debe de tener 8 componentes, minimo una mayuscula , un numero y un caracter");
    }//GEN-LAST:event_pswContraMouseClicked

    private void pswContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswContraActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int acceso=0;
        if(rbtnAlmacenista.isSelected()){acceso=1;}
        else if(rbtnCajero.isSelected()){acceso=2;}
        else if(rbtnAdministrador.isSelected()){acceso=3;}
        
        lblAviso1.setVisible(true);
        lblAviso2.setVisible(true);
        
        String contra = new String(pswContra.getPassword());
        String contra2 = new String(pswContra1.getPassword());
        String corr =txtCorreo.getText();
        if (ValidadorTexto.tieneLongitudValida(contra)&&ValidadorTexto.contieneCaracter(contra)&&
                ValidadorTexto.contieneMayuscula(contra)&&ValidadorTexto.contieneNumero(contra)){
            lblAviso1.setVisible(false);
            if(!contra.equals(contra2)){
                lblAviso.setText("La contraseña no cumple con losrequisitos para una clave segura, intenta de nuevo");
                lblAviso.setVisible(true);
            }else{
                if(!ValidadorTexto.noContieneEspacio(corr)&&!ValidadorTexto.esCorreoValido(corr)){
                    lblAviso2.setText("El correo no cumple con losrequisitos poder generar un usuario, intenta de nuevo");
                }
                else if (comparar(txtCorreo)){
                    lblAviso2.setText("El correo está repetido");
                }
                
                else{
                    
                    int opcion = JOptionPane.showConfirmDialog(
                    null, 
                    "¿Seguro que quieres crear este usuario?", 
                    "Confirmar eliminación", 
                    JOptionPane.YES_NO_OPTION
                    );

                    if (opcion == JOptionPane.YES_OPTION) {
                        lblAviso2.setVisible(false);
                        JTextField txtAccesoBotones= new JTextField();
                        txtAccesoBotones.setText(Integer.toString(acceso));
                        CUsuarios usu=new CUsuarios();
                        usu.InsertarUsuario(txtNombre,txtCorreo,pswContra,txtAccesoBotones);
                        int idFinal = usu.obtenerUltimoIdUsuario();
                        lblAviso.setText("El usuario se creó con éxito");
                        lblAviso.setVisible(true);
                        txtAsignado.setText(Integer.toString(idFinal));
                        enviarCorreo();
                    } else {
                        System.out.println("Creación cancelada.");
                    }
                }  
            }
        }else{
            if(ValidadorTexto.noContieneEspacio(corr)||!ValidadorTexto.esCorreoValido(corr)){
                    lblAviso2.setText("El correo no cumple con losrequisitos poder generar un usuario, intenta de nuevo");}
            
            lblAviso1.setText("La contraseña no cumple con los requisitos, intenta crearla de nuevo");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void pswContra1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswContra1MouseClicked
        // TODO add your handling code here:
        pswContra1.setText("");
    }//GEN-LAST:event_pswContra1MouseClicked

    private void pswContra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswContra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswContra1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Ingreso(acces,objetoUsuarios).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new opcionesPersonal(acces,objetoUsuarios).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void rbtnAlmacenistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAlmacenistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAlmacenistaActionPerformed

    private void rbtnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAdministradorActionPerformed

    private void txtAsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsignadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsignadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

            java.awt.EventQueue.invokeLater(() -> {
        CUsuarios objetoUsuarios= new CUsuarios();
        int acces=0;
        new Registro(acces,objetoUsuarios).setVisible(true); // ✅ pásala al LOGIN3
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblAviso1;
    private javax.swing.JLabel lblAviso2;
    private javax.swing.JPasswordField pswContra;
    private javax.swing.JPasswordField pswContra1;
    private javax.swing.JRadioButton rbtnAdministrador;
    private javax.swing.JRadioButton rbtnAlmacenista;
    private javax.swing.JRadioButton rbtnCajero;
    private javax.swing.JTextField txtAsignado;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
