/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login.Cajero;
import login.Cajero.CorteDeCaja_Cajero;
import com.mycompany.java_crud_mysqlfinal.CUsuarios;
import elementos.Correo;
import java.awt.Color;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
/**
 *
 * @author enriq
 */
public class EnviarMensaje extends javax.swing.JFrame {
    int acces;
    String remitente;
    String contraseña; 
    Correo miCorreo;
    String rutaArchivo;
    
    CUsuarios objetoUsuarios;
    private DefaultListModel<File> modeloArchivos = new DefaultListModel<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EnviarMensaje.class.getName());

   
    
    

    /**
     * Creates new form LOGIN
     */
    public EnviarMensaje(int acces,CUsuarios objetoUsuarios ) {
        initComponents();
        this.acces=acces;
        remitente = "enriquezvalenciaoliver501@gmail.com";
        contraseña = "cile mzdw ytpo srnu";
        miCorreo = new Correo();
        this.objetoUsuarios=objetoUsuarios;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdvertencia = new javax.swing.JLabel();
        btnMandar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        txtAsunto = new javax.swing.JTextField();
        txtMensaje = new javax.swing.JTextArea();
        btnAñadir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdvertencia.setForeground(new java.awt.Color(255, 255, 255));
        lblAdvertencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(lblAdvertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 500, 20));

        btnMandar.setText("Mandar correo");
        btnMandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMandarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel1.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("destinatario:");

        jLabel4.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("asunto:");

        jLabel5.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mensaje:");

        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });

        txtAsunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAsuntoActionPerformed(evt);
            }
        });

        txtMensaje.setColumns(20);
        txtMensaje.setRows(5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtcorreo)
                        .addComponent(txtAsunto, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                    .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 500, 230));

        btnAñadir.setText("Añadir PDFa correo");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 200, -1));

        jButton1.setText("Regresar al menú anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 200, -1));

        jLabel2.setFont(new java.awt.Font("ROG Fonts", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enviar Mensaje");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 310, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\enriq\\Desktop\\fondo1Mm.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 712));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
         JFileChooser chooser = new JFileChooser();

    // ✅ Carpeta permitida
    String rutaUsuario = System.getProperty("user.home");
    File carpetaPermitida = new File(rutaUsuario + "/Desktop/CortesDeCaja/");
    chooser.setCurrentDirectory(carpetaPermitida);

    chooser.setMultiSelectionEnabled(true);
    chooser.setDialogTitle("Selecciona archivos desde CortesDeCaja");

    int opcion = chooser.showOpenDialog(this);
    if (opcion == JFileChooser.APPROVE_OPTION) {
        File[] archivosSeleccionados = chooser.getSelectedFiles();
        boolean todosValidos = true;

        for (File archivo : archivosSeleccionados) {
            if (archivo.getAbsolutePath().startsWith(carpetaPermitida.getAbsolutePath())) {
                modeloArchivos.addElement(archivo); // ✅ Aceptado
            } else {
                todosValidos = false;
            }
        }

        if (modeloArchivos.isEmpty()) {
            lblAdvertencia.setText("Error al cargar archivos, intenta de nuevo");
            lblAdvertencia.setForeground(Color.red);
        } else if (!todosValidos) {
            lblAdvertencia.setText("Solo se permiten archivos de 'CortesDeCaja'");
            lblAdvertencia.setForeground(Color.orange);
        } else {
            lblAdvertencia.setText("Tus archivos se cargaron con éxito");
            lblAdvertencia.setForeground(Color.WHITE);
        }
    }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new CorteDeCaja_Cajero(acces,objetoUsuarios).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void txtAsuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsuntoActionPerformed

    private void btnMandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMandarActionPerformed
        // TODO add your handling code here:
        miCorreo.setRemitente(remitente,contraseña);
        miCorreo.setDestinatario(txtcorreo.getText());
        miCorreo.setContenido(txtAsunto.getText(),txtMensaje.getText());
        for (int i = 0; i < modeloArchivos.size(); i++) {
            miCorreo.agregarArchivo(modeloArchivos.get(i).getAbsolutePath());
        }
        try {
        // Envía el correo
        miCorreo.enviarCorreo();
        lblAdvertencia.setText("Correo envíado correctamente:)");
        lblAdvertencia.setForeground(Color.WHITE);

        } catch (Exception e) {
            lblAdvertencia.setText("Correo no envíado, revisa que el correo sea válido");
            lblAdvertencia.setForeground(Color.red);
            
        }
    }//GEN-LAST:event_btnMandarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

            java.awt.EventQueue.invokeLater(() -> {
        CUsuarios objetoUsuarios= new CUsuarios();
        int acces=0;
        new EnviarMensaje(acces,objetoUsuarios).setVisible(true); // ✅ pásala al LOGIN3
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnMandar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdvertencia;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextArea txtMensaje;
    private javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables
}
