package login;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */




import ProyectoTap.ValidadorTexto;
import com.mycompany.java_crud_mysqlfinal.CConexion;
import com.mycompany.java_crud_mysqlfinal.CUsuarios;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.util.ArrayList;
/**
 *
 * @author enriq
 */
public class Ingreso extends javax.swing.JFrame {
  String usuario, contrasena;
    int acces;
    CUsuarios objetoUsuarios;
    CConexion objetoConexion;
    ArrayList<String> rutas;
    ArrayList<String> valores;
    int i;
    String valor;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ingreso.class.getName());

    /**
     * Creates new form LOGIN
     */
    public Ingreso(int acces, CUsuarios objetoUsuarios) {
        initComponents();
        lblAviso.setVisible(false);
        this.acces=acces;
        this.objetoUsuarios=objetoUsuarios;
        rutas = new ArrayList<>();
        rutas.add("/login/Imagenes/cap1.png");
        rutas.add("/login/Imagenes/cap2.png");
        rutas.add("/login/Imagenes/cap3.png");
        i=0;
        
        valores = new ArrayList<>();
        valores.add("nsP58q");
        valores.add("YBDM");
        valores.add("H6V5K");
        
        String valor="";
        lblAviso.setVisible(false);
        Imagen(rutas.get(0),valores.get(0));
    }
    
    
    public boolean comparar(JTextField correo, String contra){
        objetoConexion=new CConexion();
        Statement st;
        String sql = "";
        sql="SELECT * FROM usuarios;";
        try{
            st= objetoConexion.estableceConexion().createStatement();
            ResultSet rs =st.executeQuery(sql);
            while (rs.next()){
                if (rs.getString(3).equals(correo.getText())){
                    acces= rs.getInt(1);
                    return rs.getString(4).equals(contra);
                }           
            }
            
        }
        catch(SQLException e){JOptionPane.showMessageDialog(null, " No se pudo acceder a la BD");}
        return false;
    }
    
    public void Imagen(String ruta,String valoress) {
        // Ruta relativa al paquete src/login/Imagenes/
        valor=valoress;
        String rutaImagen = ruta; // Asegúrate de usar el nombre y extensión correctos

        java.net.URL recurso = getClass().getResource(rutaImagen);
    
        if (recurso != null) {
            ImageIcon icono = new ImageIcon(recurso);

            // Escalar imagen al tamaño del JLabel
            int ancho = lblImagen.getWidth();
            int alto = lblImagen.getHeight();
            Image imagenEscalada = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

            lblImagen.setIcon(new ImageIcon(imagenEscalada));
        } else {
            JOptionPane.showMessageDialog(null, "⚠ Imagen no encontrada en: " + rutaImagen);
            lblImagen.setIcon(null);
        }
    }


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        txtCap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pswContra = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        lblAviso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCap = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("R");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 40, 30));

        lblImagen.setForeground(new java.awt.Color(255, 255, 255));
        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 170, 50));
        jPanel1.add(txtCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 170, -1));

        jLabel2.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CORREO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtCorreo.setText("@gmail.com");
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 233, -1));

        jLabel3.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTRASEÑA:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        pswContra.setText("jPasswordField1");
        pswContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pswContraMouseClicked(evt);
            }
        });
        pswContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswContraActionPerformed(evt);
            }
        });
        jPanel1.add(pswContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 233, -1));

        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Imagenes/imagen_2025-07-25_022338477.png"))); // NOI18N
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setFocusPainted(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 50, 50));

        lblAviso.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblAviso.setForeground(new java.awt.Color(255, 0, 0));
        lblAviso.setText("Usuario o  contraseña incorecta, intenta de nuevo");
        jPanel1.add(lblAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 310, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Imagenes/usuario(1) (1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 100, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Imagenes/cerrar-con-llave.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 30, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Imagenes/correo-electronico.png"))); // NOI18N
        jLabel9.setText("jLabel7");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 30, 30));

        lblCap.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCap.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 310, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Imagenes/vladislav-bychkov-NdbdD6matvE-unsplash (1).jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        String contra = new String(pswContra.getPassword());
        if(comparar(txtCorreo,contra)){
            if(txtCap.getText().equals(valor)){
                new Menu_Principal(acces,objetoUsuarios).setVisible(true);
                this.dispose();
            }
            lblCap.setText("Captcha incorrecto, intenta de nuevo");
            
        }else{
            lblAviso.setVisible(true);
            System.out.println("aqui");
        }
        
        /* TODO add your handling code here:
        String contra = new String(pswContra.getPassword());
        
        int i=0;
        if(array.returnArreglo().isEmpty())System.out.println("sin usuarios");
        while(i<=array.returnArreglo().size()-1){
            if(!(txtCorreo.getText().equals(array.returnArreglo().get(i).getCorreo()))||!array.returnArreglo().get(i).getContra().equals(contra)){
                lblAviso.setVisible(true);
                System.out.println(txtCorreo.getText());
                System.out.println(array.returnArreglo().get(i).getCorreo());
            }else{
                new LOGIN2(array,objetoUsuarios).setVisible(true);
                this.dispose();
            }
            i++;
        }*/
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void pswContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswContraActionPerformed

    private void pswContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswContraMouseClicked
        // TODO add your handling code here:
        pswContra.setText("");
    }//GEN-LAST:event_pswContraMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
        txtCorreo.setText("");
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lblCap.setText("");
        i++;
        if(i==3){i=0;}
        if (i==0){
            Imagen(rutas.get(0),valores.get(0));
        }
        else if(i==1){            
          Imagen(rutas.get(1),valores.get(1));  
        }
        else{
            Imagen(rutas.get(2),valores.get(2));
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

            java.awt.EventQueue.invokeLater(() -> {
        CUsuarios objetoUsuarios= new CUsuarios();   
        int acces=0;
        new Ingreso(acces,objetoUsuarios).setVisible(true); // ✅ pásala al LOGIN3
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblCap;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPasswordField pswContra;
    private javax.swing.JTextField txtCap;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables

    
}
